[settings]
experimental = true

[tools]
ruby = "3.4.3"
go = "latest"
node = "24"
python = "latest"
lua = "5.4"
"gem:rubocop" = "latest"
"gem:neovim" = "latest"
"npm:prettier" = "latest"
"npm:neovim" = "latest"
"asdf:mise-plugins/mise-lua" = "latest"
